name: pokedex
description: "A Pok√©Dex Flutter application that displays Pokemon information using BLoC state management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  
  # Networking
  http: ^1.4.0
  
  # Caching for images
  cached_network_image: ^3.4.1
  
  # Icons
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/icons/
    - assets/icons/
